### ISSUE TITLE
two way binding is not working

### ISSUE THREAD

**Issue by lostlian** [alexiscolin/vue-timeselector#1]
Hi! I am really loving this vue plugin. Thanks for it. 

Im having trouble making work the two way binding. 

Lets supose

```
<timeselector v-model="time" :name="uniquename"></timeselector>
```

then if i do something like this. 

```
this.time = someNewDate;
```

It updates de property called _value_

but it doesnt update the displayed value in the picker. 

how can i update the time from a parent component?

**Comment by alexiscolin** [comment]
Hi! Thank you for your support.

Actually, I understand your trouble. I disabled two-way-binding by putting `this.value` out of `computed` reactivity process. The value is calculated at the creation directly in the `data`.

```
data () {
  return {
    picker: {
      hour: this.value ? (this.utc ? this.value.getUTCHours() : this.value.getHours()) : 0,
      minute: this.value ? (this.utc ? this.value.getUTCMinutes() : this.value.getMinutes()) : 0,
      second: this.value ? (this.utc ? this.value.getUTCSeconds() : this.value.getSeconds()) : 0,
      ...
    }
  }
}
```

I did that because of the `returnFormat` prop that can create a conflict with time format when the time is recalculated after a selection. 

Imagine that you get a returned time through the component like `12 hours and 23m`, if the two-way-binding is activated, the component will recalculate the time over a dirty value: `12 hours and 23m` -> not good for `getHours` method...

Maybe we can enable it only if the `returnFormat` is disabled as well. Do you have an idea about it ?

**Comment by lostlian** [comment]
what if you create a watcher on the value property. that "emulates" the picker selection. 

So if value property is changed. you can easily set time. 

```
watch:
{
        'value'()
        {
            this.picker.hour = this.value ? (this.utc ? this.value.getUTCHours() : this.value.getHours()) : 0;
            this.picker.minute = this.value ? (this.utc ? this.value.getUTCMinutes() : this.value.getMinutes()) : 0;
            this.picker.second = this.value ? (this.utc ? this.value.getUTCSeconds() : this.value.getSeconds()) : 0;
            this.picker.selected.hour = this.picker.hour
            this.picker.selected.minute = this.picker.minute
            this.picker.selected.second = this.picker.second
            this.picker.time = this.value;
        },
...
}
```


i just test it and worked like a charm!

**Comment by lostlian** [comment]
Im sorry alexis I can't find the problems with returnFormat. 

What is weird for me is that we can bind a v-model but is not two way binding. Is working as a normal property not binded so it would be the same as `:value="something"`

you say you can emit the value or set a new value in a computed property. But in this cases. How can I edit the time from the outside?

so far i did it like this and it worked.
```
<timeselector v-model="event.end_time" :display-format="'HH:mm'" name="end_time" ref="end_time"></timeselector>
```
**when a startDate is later than endTime. I sync them for consistency**
```
end_date = start_date;
this.event.end_time = new Date(end_date.toISOString());
this.$refs.end_time.picker.hour = this.event.end_time.getHours();
this.$refs.end_time.picker.minute = this.event.end_time.getMinutes();
this.$refs.end_time.picker.second = this.event.end_time.getSeconds();
this.$refs.end_time.picker.selected.hour = this.event.end_time.getHours();
this.$refs.end_time.picker.selected.minute = this.event.end_time.getMinutes();
this.$refs.end_time.picker.selected.second = this.event.end_time.getSeconds();
this.$refs.end_time.picker.time = this.event.end_time;
```

so if i need to update the value from the outside im forcing it. I know it's not right. 

could you explain to me further what are the problems with the returnFormat property? give me a format that would make it fail

**Comment by alexiscolin** [comment]
I understand your problem and what you want to achieve. I think there are a misunderstanding with `returnedFormat` property. I've just created a pull request #2 with that feature enabled (two way binding). You can check if it solves your issue. I changed `returnedFormat` in order to make it as an event emited and not a "getter" transformer for value.

**Comment by lostlian** [comment]
I tried it. But it doesnt update the picker selection

<img width="708" alt="captura de pantalla 2019-01-21 11 41 26" src="https://user-images.githubusercontent.com/51205/51487647-90d68a80-1d71-11e9-9a7d-0caaf1160c72.png">

The "11" should be selected not the "1"

**Comment by alexiscolin** [comment]
My bad! now I (really) understand what you want to achieve. So yes, a watcher should be a good option. I'm going to implement it as you propose (with some adjustments for AMPM time format).

**Comment by alexiscolin** [comment]
I just push another version on that branch, that I need to review. That will let you see the component act like you wish. Let me know.

**Comment by alexiscolin** [comment]
Thank you for your suggestions and your help, I just pushed the new version on the master branch and published it on npm. I hope you will enjoy it.

**Comment by lostlian** [comment]
Hello Alexis! Im sorry to re open the issue. but it looks like the dist folder was not updated. And when I import it `import Timeselector from 'vue-timeselector';` it looks for that compiled dist file. 

I tooked the component out, webpack it and it works fine standalone so it only needs to be compiled it 

can you please compile it so the dist folder gets updated as well?

Thanks a lot!

**Comment by alexiscolin** [comment]
I'm confused, I just published a complete Dist version. 
Thank you

**Comment by BaiMaoLi** [comment]
Hi, alexiscolin, 
**Two way data binding still not working.**
<div class="form-group">
                    <label>Begginging Time</label>
                    <time-selector v-model="default_begin_time" :required="true" :disabled="false" :interval="{h:1, m:30}" :displayFormat="'HH : mm'" :utc="false" placeholder="Selec ending time"></time-selector>
                </div>
                <div class="form-group" style="margin-left:20px;">
                    <label>Ending Time</label>
                    <time-selector v-model="default_end_time" :required="true" :disabled="false" :interval="{h:1, m:30}" :displayFormat="'HH : mm'" placeholder="Selec ending time"></time-selector>
                </div>

I have default_begin_time, and default_ending_time data.
and when default_begin_time changing, I want to change other null day hours.
days:
                    [
                        {
                            day:'Sun',
                            begin_time:new Date(),
                            ending_time:'',
                            working:true
                        },
                        {
                            day:'Mon',
                            begin_time:null,
                            ending_time:'',
                            working:true
                        },
                        {
                            day:'Tue',
                            begin_time:null,
                            ending_time:'',
                            working:true
                        },
                        {
                            day:'Wed',
                            begin_time:null,
                            ending_time:'',
                            working:true
                        },
                        {
                            day:'Thu',
                            begin_time:null,
                            ending_time:'',
                            working:true
                        },
                        {
                            day:'Fri',
                            begin_time:null,
                            ending_time:'',
                            working:true
                        },
                        {
                            day:'Sat',
                            begin_time:null,
                            ending_time:'',
                            working:true
                        },
                    ],

and my watch for default_begin_time is as follows.

watch:{
            default_begin_time:function(newValue,oldValue){
                console.log(newValue);
                console.log(typeof newValue)
                for(let i=0;i<this.days.length;i++){
                    if (this.days[i]['working'] && !this.days[i]['begin_time']){
                        this.days[i]['begin_time']=newValue;
                    }
                }


            }
        },

It is updating days[i]['begin_time'], but not updating time on component,
I am wasting full day.
can you help me with that?
